{% set name = "jwskate" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jwskate-{{ version }}.tar.gz
  sha256: 35354b487c8e835fdd57befea5e93e9e52fe25869d884fc764511d22061e6685

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - cryptography >=3.4
    - typing-extensions >=4.3
    - binapy >=0.8

test:
  imports:
    - jwskate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/guillp/jwskate
  doc_url: https://guillp.github.io/jwskate/
  summary: A Pythonic implementation of the JOSE / JSON Web Crypto related RFCs (JWS, JWK, JWA, JWT, JWE)
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
