{% set name = "jwskate" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jwskate-{{ version }}.tar.gz
  sha256: 7c38b036b633d689b31c89b358823dbc8c439e4c74596cb1fceb0dfe4cf9efce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - cryptography >=3.4
    - typing-extensions >=4.3
    - binapy >=0.8

test:
  imports:
    - jwskate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/guillp/jwskate
  doc_url: https://guillp.github.io/jwskate/
  summary: A Pythonic implementation of the JOSE / JSON Web Crypto related RFCs (JWS, JWK, JWA, JWT, JWE)
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
